source 'https://github.com/CocoaPods/Specs.git'

# workaround for https://github.com/CocoaPods/CocoaPods/issues/8073
install! 'cocoapods', :disable_input_output_paths => true

# ignore all warnings from all pods
inhibit_all_warnings!

use_frameworks!
platform :ios, '11.0'

target 'TestProj' do
  # MultiPlatformLibrary
  pod 'MultiPlatformLibrary', :path => '../mpp-library'
end

# GoogleMaps is statically linked to moko-maps-google, so we should remove duplication liking
post_install do |installer|
  host_targets = installer.aggregate_targets.select { |aggregate_target|
    aggregate_target.name.include? "Pods-"
  }

  host_targets.each do |host_target|
    host_target.xcconfigs.each do |config_name, config_file|
      config_file.frameworks.delete("GoogleMaps")
      config_file.frameworks.delete("GoogleMapsBase")
      config_file.frameworks.delete("GoogleMapsCore")

      xcconfig_path = host_target.xcconfig_path(config_name)
      config_file.save_as(xcconfig_path)
    end
  end
end
